In [1]:
fichier = open("iris.csv")
import csv
lecteur = csv.reader(fichier)
for ligne in lecteur:
    if(lecteur.line_num == 1):
        n = int(ligne[0])
        p = int(ligne[1])
        c = int(ligne[2])
        X = []
        D = []
    else:
        X.append([float(ligne[i]) for i in range(p)])
        D.append(int(ligne[p]))
#print(X[:][0])
import numpy as np
X = np.array(X)
#print(X[:,0])
#print(D)

In [2]:
import random as rd
class FCM:
    def __init__(self, m, c, X):
        self.m = m
        self.c = c
        self.p = X.shape[1]
        minX = [min(X[:,i]) for i in range(self.p)]
        maxX = [max(X[:,i]) for i in range(self.p)]
        self.V = np.array([ [ rd.uniform(minX[j], maxX[j]) for j in range(self.p)] for i in range(self.c)])
        self.U = []
        self.Etqt = []
    def calculerU(self, X):
        alpha = -1./(self.m-1.)
        term1 = [ [ pow(sum(np.square(X[k]-self.V[i])), alpha) for k in range(X.shape[0]) ] for i in range(self.c)]
        term2 = [ sum([pow(sum(np.square(X[k]-self.V[i])), alpha) for i in range(self.c)]) for k in range(X.shape[0])]
        self.U = [ [ term1[i][k]/term2[k] for k in range(X.shape[0])] for i in range(self.c)]
    def calculerV(self, X):
        card = [ sum([pow(self.U[i][k], self.m) for k in range(X.shape[0])]) for i in range(self.c)]
        #print(sum(card)) #à cause de la puissance m, la somme est différente de n
        term = [ [ sum([ pow(self.U[i][k], self.m)*X[k][j] for k in range(X.shape[0])]) for j in range(self.p)] for i in range(self.c)]
        self.V = [ [ term[i][j]/card[i] for j in range(self.p)] for i in range(self.c)]
    def entrainer(self, X, tmax, eps):
        t = 1
        while(t<tmax):
            self.calculerU(X)
            self.calculerV(X)
            t = t + 1
            self.etiqueterV(X)
            print(self.tauxErr(X, D)*100./X.shape[0],"%")
    def etiqueterV(self, X):
        card = [0 for i in range(self.c)]
        Vmoy = [ [ 0. for j in range(self.p)] for i in range(self.c)]
        for k in range(X.shape[0]):
            for j in range(self.p):
                Vmoy[D[k]-1][j] = Vmoy[D[k]-1][j] + X[k][j]
        for k in range(X.shape[0]):
            card[D[k]-1] = card[D[k]-1] + 1
        for i in range(self.c):
            for j in range(self.p):
                Vmoy[i][j] = Vmoy[i][j] / card[D[k]-1]
        Vmoy = np.array(Vmoy)
        #print("Vmoy = \n"+str(np.array(Vmoy)))
        dist = [[sum(np.square(self.V[l]-Vmoy[i])) for i in range(self.c)] for l in range(self.c)]
        etqt = [np.argmin(dist[i]) for i in range(self.c)]
        for i in range(self.c):
            self.Etqt.append(etqt[i]+1)
        #print(np.array(self.Etqt))
    def classe(self, vect):
        term1 = [ pow(sum(np.square(vect-self.V[i])), -1./(self.m-1)) for i in range(self.c)]
        term2 = sum([ pow(sum(np.square(vect-self.V[i])), -1./(self.m-1)) for i in range(self.c)])
        u = [term1[i]/term2 for i in range(self.c)]
        return self.Etqt[np.argmax(u)]
    def tauxErr(self, X, D):
        er = 0.
        for k in range(X.shape[0]):
            if(self.classe(X[k]) != D[k]):
                er = er + 1
        return er

In [3]:
fcm = FCM(2, c, X)
fcm.calculerU(X)
#for i in range(X.shape[0]):
#    print(np.array(fcm.U)[:,i])
fcm.calculerV(X)
print(np.array(fcm.V))
print()

fcm.entrainer(X, 1000, 0.001)
print(np.array(fcm.V))
print()

print(fcm.tauxErr(X, D)*100./X.shape[0],"%") 

[[6.07371988 2.88168941 4.65124691 1.57644857]
 [5.0614363  3.41837309 1.64217594 0.31998194]
 [6.51812537 2.93548502 5.04481584 1.71314232]]

10.666666666666666 %
10.0 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.6666666

10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.6666666666

10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.666666666666666 %
10.6666666666

In [4]:
import random as rd
class LVQ:
    def __init__(self, m, c, X):
        self.m = m
        self.c = c
        self.p = X.shape[1]
        minX = [min(X[:,i]) for i in range(self.p)]
        maxX = [max(X[:,i]) for i in range(self.p)]
        self.V = np.array([ [ rd.uniform(minX[j], maxX[j]) for j in range(self.p)] for i in range(self.c)])
        self.U = []
        self.Etqt = []      
    def calculerV(self, X,eta):
        self.V += eta*(X[k]-self.V)
    def entrainer(self, X, tmax, eps):
        t = 1
        while(t<tmax):
            self.calculerU(X)
            self.calculerV(X)
            t = t + 1
            self.etiqueterV(X)
            print(self.tauxErr(X, D)*100./X.shape[0],"%")
    def etiqueterV(self, X):
        card = [0 for i in range(self.c)]
        Vmoy = [ [ 0. for j in range(self.p)] for i in range(self.c)]
        for k in range(X.shape[0]):
            for j in range(self.p):
                Vmoy[D[k]-1][j] = Vmoy[D[k]-1][j] + X[k][j]
        for k in range(X.shape[0]):
            card[D[k]-1] = card[D[k]-1] + 1
        for i in range(self.c):
            for j in range(self.p):
                Vmoy[i][j] = Vmoy[i][j] / card[D[k]-1]
        Vmoy = np.array(Vmoy)
        #print("Vmoy = \n"+str(np.array(Vmoy)))
        dist = [[sum(np.square(self.V[l]-Vmoy[i])) for i in range(self.c)] for l in range(self.c)]
        etqt = [np.argmin(dist[i]) for i in range(self.c)]
        for i in range(self.c):
            self.Etqt.append(etqt[i]+1)
        #print(np.array(self.Etqt))
    def classe(self, vect):
        term1 = [ pow(sum(np.square(vect-self.V[i])), -1./(self.m-1)) for i in range(self.c)]
        term2 = sum([ pow(sum(np.square(vect-self.V[i])), -1./(self.m-1)) for i in range(self.c)])
        u = [term1[i]/term2 for i in range(self.c)]
        return self.Etqt[np.argmax(u)]
    def tauxErr(self, X, D):
        er = 0.
        for k in range(X.shape[0]):
            if(self.classe(X[k]) != D[k]):
                er = er + 1
        return er

In [7]:
import numpy as np
import random as rd
class LVQ:
    def __init__(self, m, c, eta,t_max,X):
        self.m = m
        self.c = c
        self.p = X.shape[1]
        minX = [min(X[:,i]) for i in range(self.p)]
        maxX = [max(X[:,i]) for i in range(self.p)]
        self.V = np.array([ [ rd.uniform(minX[j], maxX[j]) for j in range(self.p)] for i in range(self.c)])
        self.eta=eta
        self.t_max=t_max
    def gagnant(self,x):
        g=np.argmin([sum(np.square(x-self.V[i]))for i in range(self.c)])
        return g
    def ajuster(self,x,g):
        self.V[g]+=self.eta*(x-self.V[g])

    def entrainer(self,X):
        for t in range(self.t_max):
            for k in range(X.shape[0]):
                self.ajuster(X[k],self.gagnant(X[k]))
    def afficher(self):
        print(self.V)
    def desision(self,X):
        decision=[]
        for i in range(X.shape[0]):
            decision.append(np.argmin([sum(np.square(X[i]-self.V[j])) for j in range(self.c)]))
        return [d + 1 for d in decision]


In [8]:
lvq=LVQ(2,3,0.2,1000,X)
print('les prototypes avant l entrainement :')
lvq.afficher()
lvq.entrainer(X)
print('les prototypes apres l entrainement :')
lvq.afficher()
print(lvq.desision(X))

les prototypes avant l entrainement :
[[4.74110484 2.68119334 5.90308945 1.71110615]
 [6.64894271 3.84582964 3.82524124 1.76898773]
 [6.44899259 3.46713976 4.22013324 1.53808881]]
les prototypes apres l entrainement :
[[6.62946492 3.16403886 5.47517107 2.23081586]
 [4.9552498  3.39914833 1.47075856 0.2477971 ]
 [6.00351005 2.76524099 4.98439872 1.74671368]]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 1, 3, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3, 1, 3, 3, 1, 1, 1, 1, 3, 1, 3, 1, 3, 1, 1, 3, 3, 1, 1, 1, 1, 1, 3, 3, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 1, 3, 1, 1, 3]
